spring.application.name=campus

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/campus}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:hfpatel}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}