spring.application.name=campus
spring.datasource.url=jdbc:postgresql://localhost:5432/campus
spring.datasource.username=hfpatel
spring.jpa.hibernate.ddl-auto=update
spring.data.redis.host=localhost
spring.data.redis.port=6379